version: 2
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "fc:7f:53:3f:c1:1a:17:75:07:2c:b7:08:40:5b:dc:82" #上記メモったハッシュを指定
      - run:
        name: Deploy Over SSH
        command: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/html/circleci/deploy-me.sh"
 
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master